config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :bloods, only: [:index, :new, :show, :create] do
    resources :donations, only: [:create]
  end
  get '/my_donations', to: 'pages#my_donations', as: :my_donations
  # get '/my_donations', to: 'pages#my_donations'
  get '/all_donations', to: 'pages#all_donations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood.rb
class Blood < ApplicationRecord
  BLOOD_TYPE = %w[A+ A- B+ B- AB+ AB- O+ O- De\ Barata Frio Quente Fervendo Azul]

  belongs_to :user
  has_many :donations
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :address, presence: true
  validates :blood_type, inclusion: { in: BLOOD_TYPE }
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :blood
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :donations
  has_many :bloods
  validates :cpf, presence: { if: -> { cnpj.blank? } }
  validates :cnpj, presence: { if: -> { cpf.blank? } }
  validates :address, :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

def skip_pundit?
  devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
end

def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up,
                                    keys: %i[name])

  # For additional in app/views/devise/registrations/edit.html.erb
  devise_parameter_sanitizer.permit(:account_update,
                                    keys: %i[name])
end
end

app/controllers/bloods_controller.rb
class BloodsController < ApplicationController
  def new
    @blood = Blood.new
  end

  def index
    @bloods = Blood.where.not(latitude: nil, longitude: nil, available: true)

    @markers = @bloods.geocoded.map do |blood|
      {
        lat: blood.latitude,
        lng: blood.longitude,
        info_window: render_to_string(partial: "info_window", locals: { blood: blood })
      }
    end
  end

  def show
    @blood = Blood.find(params[:id])
  end

  def create
    @blood = Blood.new(blood_params)
    @blood.user = current_user
    @blood.address = current_user.address if @blood.address.empty?
    @blood.offer = current_user.cnpj.nil?

    if @blood.save
      redirect_to my_donations_path
    else
      render :new
    end
  end

  private

  def blood_params
    params.require(:blood).permit(:blood_type, :address)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def show
    @donation = Donation.find(params[:id])
  end

  def create
    @donation = Donation.new(blood: Blood.find(params[:blood_id]))
    if current_user.cnpj.nil?
      @donation.user = @donation.blood.user
      @donation.blood.update(user: current_user, offer: true, available: false)
    else
      @donation.user = current_user
      @donation.blood.update(available: false)
    end

    if @donation.save
      redirect_to my_donations_path
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @bloods = Blood.all
  end

  def my_donations
    @bloods = current_user.bloods
    if current_user.cnpj.nil?
      @donations = Donation.includes(blood: [:user]).where(bloods: { user: current_user })
    else
      @donations = current_user.donations
    end
  end

  def all_donations
    @bloods = if current_user.cnpj.nil?
                Blood.where(offer: false)
              else
                Blood.where(offer: true)
              end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bloods/_info_window.html.erb
<h2><%= blood.blood_type %></h2>
<p><%= blood.address %></p>

app/views/bloods/index.html.erb
<div class="container">
<h1>Hospitais precisando de Sangue, <a href="">doe já.</a></h1>


<div id="map"
     style="width: 100px; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/bloods/new.html.erb
  <div class="container pt-5 mt-5">
    <h1>Blood Donation</h1>
    <%= simple_form_for @blood do |f| %>
      <%= f.input :blood_type, collection: Blood::BLOOD_TYPE %>
      <%= f.input :address, placeholder: 'Leave it blank to user your own address', required: false%>
      <%= f.submit 'BLOOD!'%>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Blood Donation Center</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>

  <header>
    <div class="w-100 bg-light pb-3 pt-3 fixed-top">
      <% nav_class = request.env['PATH_INFO'] == '/' ? 'btn-outline-dark' : 'btn-outline-dark' %>
      <div class="ml-3">
        <% if current_user %>
        <div class="text-end mx-2 mt-2">
        <%= link_to current_user.name, '#', class:"btn #{nav_class} me-2 mr-3" %>
        <%= link_to 'Blood Donation Center', root_path, class:"btn #{nav_class} me-2" %>
        <%= link_to 'Donate Now', new_blood_path, class:"btn #{nav_class} me-2" %>
        <%# <button type="button" class="btn btn-danger">Donate</button> %>
        <%= link_to 'My Donations', my_donations_path, class:"btn #{nav_class} me-2" %>
        <%= link_to 'Offers and Requests', all_donations_path, class:"btn #{nav_class} me-2" %>
        <%# <button type="button" class="btn btn-danger">My Donations</button> %>
        <%= link_to 'Log out', destroy_user_session_path, class:"btn btn-outline-danger my-2 my-sm-0", method: :delete %>
        <%# <button type="button" class="btn #{nav_class} me-2">Sign-out</button> %>
        <% else  %>
        <%= link_to 'Offers and Requests', all_donations_path, class:"btn #{nav_class} me-2" %>
        <%= link_to 'Blood Donation Center', root_path, class:"btn #{nav_class} me-2" %>
        <%= link_to 'Donate Now', new_blood_path, class:"btn #{nav_class} me-2" %>
        <%# <button type="button" class="btn btn-danger">Donate</button> %>
        <%= link_to 'My Donations', my_donations_path, class:"btn #{nav_class} me-2" %>
        <%= link_to 'Login', new_user_session_path, class:"btn btn-success my-2" %>
        <%# <button type="button" class="btn btn-danger">Login</button> %>
        <% end %>
        </div>
      </div>
    </div>
  </header>
  <div>
    <%= yield %>
  </div>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/layouts/login.erb
<main class="form-signin text-center">
  <form>
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" kl_vkbd_parsed="true">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" kl_vkbd_parsed="true">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me" kl_vkbd_parsed="true"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
  </form>
</main>

app/views/pages/all_donations.html.erb
<div class='container pt-5 mt-3'>
  <div class='d-flex justify-content-between my-4'>
    <h1><%= current_user.cnpj.nil? ? 'Blood Requests' : 'Donations Available' %></h1>
  </div>
  <div>
    <table class="table table-hover">
      <thead class="text-dark">
        <tr>
          <th scope="col"><%= current_user.cnpj.nil? ? 'Hospital' : 'User' %></th>
          <th scope="col">Blood Type</th>
          <th scope="col">Address</th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <tbody>
          <% @bloods.each do |blood|  %>
            <% if current_user.cnpj != nil %>
              <tr>
                <td scope="col"><%= blood.user.name %></td>
                <td scope="col"><%= blood.blood_type  %></td>
                <td scope="col"><%= blood.address  %></td>
                <td scope="col"><%= link_to 'Accept', blood_donations_path(blood), method: :post %></td>
              </tr>
            <% else %>
              <tr>
                <td scope="col"><%= blood.user.name %></td>
                <td scope="col"><%= blood.blood_type  %></td>
                <td scope="col"><%= blood.address  %></td>
                <td scope="col"><%= link_to 'Donate', blood_donations_path(blood), method: :post %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/pages/home.html.erb
<%# <div id="carouselExampleCaptions" class="carousel slide bg-dark" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner bg-dark">
    <div class="carousel-item active">
      <img src="https://tinyurl.com/53hxjr3d" class="d-block w-100">

    </div>
    <div class="carousel-item bg-dark">
      <img src="https://images.unsplash.com/photo-1615461066841-6116e61058f4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1448&q=80" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <button type="button" class="btn btn-outline-danger bg-dark">Second slide label</button>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev bg-dark" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next bg-dark" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div> %>

  <img src="https://tinyurl.com/53hxjr3d" alt="" class=" w-100">

app/views/pages/my_donations.html.erb
<div class='container pt-5 mt-3'>
  <% if current_user.cnpj != nil %>
    <div class='d-flex justify-content-between my-4 class='>
      <h1>My Recieved Donations</h1>
    </div>
  <% else %>
    <div class='d-flex justify-content-between my-4 class='>
      <h1>My Donations</h1>
    </div>
  <% end %>
  <div>
    <table class="table table-hover">
        <tbody>
          <% if current_user.cnpj != nil %>
            <thead class="text-dark">
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Blood Type</th>
                <th scope="col">Address</th>
              </tr>
            </thead>
          <% else %>
            <thead class="text-dark">
              <tr>
                <th scope="col">Blood Type</th>
                <th scope="col">Hospital</th>
                <th scope="col">Available</th>
              </tr>
            </thead>
          <% end %>
          <% if current_user.cnpj != nil %>
            <% @donations.each do |donation|  %>
              <tr>
                <td scope="col"><%= donation.blood.user.name %></td>
                <td scope="col"><%= donation.blood.blood_type %></td>
                <td scope="col"><%= donation.blood.address %></td>
              </tr>
            <% end %>
          <% else %>
            <% @bloods.each do |blood|  %>
              <tr>
                <td scope="col"><%= blood.blood_type %></td>
                <td scope="col"><%= blood.donations.empty? ? 'Unclaimed' : blood.donations.first.user.name %></td>
                <td scope="col"><%= blood.available ? 'Yes' : 'No' %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/pages/user_donations.html.erb
<div class='container'>
  <div class='d-flex justify-content-between my-4'>
    <h1>My Donations</h1>
    <%= link_to 'Back', root_path, class:'btn-danger btn' %>
  </div>
  <div>
    <table class="table">
      <thead class="bg-danger text-white">
        <tr>
          <th scope="col">User</th>
          <th scope="col">Blood Quantity</th>
          <th scope="col">Location</th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <tbody>
          <tr>
            <td scope="col"><%= User.donation %></td>
          </tr>
          <% end  %>
        </tbody>
    </table>
  </div>
</div>